<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Intro to ANOVA Analysis | R Guides</title>
  <meta name="description" content="Chapter 3 Intro to ANOVA Analysis | R Guides" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Intro to ANOVA Analysis | R Guides" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Intro to ANOVA Analysis | R Guides" />
  
  
  

<meta name="author" content="Mr. Ng &amp; Others" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro-to-two-sample-t-tests.html"/>
<link rel="next" href="references.html"/>
<script src="book_assets/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="book_assets/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="book_assets/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="book_assets/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="book_assets/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="book_assets/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#casper-biting"><i class="fa fa-check"></i>Casper Biting</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#casper-sleeping"><i class="fa fa-check"></i>Casper Sleeping</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html"><i class="fa fa-check"></i><b>1</b> Census Data and Linear Regression</a>
<ul>
<li class="chapter" data-level="1.1" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html#install-packages-and-census-api-key"><i class="fa fa-check"></i><b>1.1</b> Install packages and Census API Key</a></li>
<li class="chapter" data-level="1.2" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html#pull-data-from-the-census"><i class="fa fa-check"></i><b>1.2</b> Pull data from the Census</a></li>
<li class="chapter" data-level="1.3" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html#construct-a-linear-model"><i class="fa fa-check"></i><b>1.3</b> Construct a Linear Model</a></li>
<li class="chapter" data-level="1.4" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html#create-two-data-displays."><i class="fa fa-check"></i><b>1.4</b> Create two data displays.</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="census-data-and-linear-regression.html"><a href="census-data-and-linear-regression.html#how-to-remove-nas"><i class="fa fa-check"></i><b>1.4.1</b> How to remove NA’s</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html"><i class="fa fa-check"></i><b>2</b> Intro to Two-Sample T-Tests</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#loading-data."><i class="fa fa-check"></i><b>2.1</b> Loading Data.</a></li>
<li class="chapter" data-level="2.2" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#data-wrangling"><i class="fa fa-check"></i><b>2.2</b> Data Wrangling</a></li>
<li class="chapter" data-level="2.3" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#isolate-the-variables-of-interest."><i class="fa fa-check"></i><b>2.3</b> Isolate the variables of interest.</a></li>
<li class="chapter" data-level="2.4" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#graph-boxplots."><i class="fa fa-check"></i><b>2.4</b> Graph boxplots.</a></li>
<li class="chapter" data-level="2.5" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#run-a-two-sample-t-test."><i class="fa fa-check"></i><b>2.5</b> Run a Two Sample T-Test.</a></li>
<li class="chapter" data-level="2.6" data-path="intro-to-two-sample-t-tests.html"><a href="intro-to-two-sample-t-tests.html#graph-the-t-distribution-and-test-statistic."><i class="fa fa-check"></i><b>2.6</b> Graph the t-distribution and test statistic.</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html"><i class="fa fa-check"></i><b>3</b> Intro to ANOVA Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#comparing-several-means-hummingbirds-and-tropical-flowers"><i class="fa fa-check"></i><b>3.1</b> Comparing Several means: Hummingbirds and Tropical Flowers</a></li>
<li class="chapter" data-level="3.2" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#the-f-test"><i class="fa fa-check"></i><b>3.2</b> The F Test</a></li>
<li class="chapter" data-level="3.3" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#check-for-conditions"><i class="fa fa-check"></i><b>3.3</b> Check for Conditions</a></li>
<li class="chapter" data-level="3.4" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#the-f-distribution"><i class="fa fa-check"></i><b>3.4</b> The F Distribution</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#finding-the-degrees-of-freedom-for-f"><i class="fa fa-check"></i><b>3.4.1</b> Finding the Degrees of Freedom for F</a></li>
<li class="chapter" data-level="3.4.2" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#understanding-the-f-statistic"><i class="fa fa-check"></i><b>3.4.2</b> Understanding the F Statistic</a></li>
<li class="chapter" data-level="3.4.3" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#calculate-the-f-statistic"><i class="fa fa-check"></i><b>3.4.3</b> Calculate the F Statistic</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#conducting-the-one-way-anova"><i class="fa fa-check"></i><b>3.5</b> Conducting the one-way ANOVA</a></li>
<li class="chapter" data-level="3.6" data-path="intro-to-anova-analysis.html"><a href="intro-to-anova-analysis.html#conclude-pt.-2-creating-tukey-post-hoc-pairwise-comparisons"><i class="fa fa-check"></i><b>3.6</b> Conclude Pt. 2: Creating Tukey Post-Hoc Pairwise Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R Guides</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intro-to-anova-analysis" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Intro to ANOVA Analysis<a href="intro-to-anova-analysis.html#intro-to-anova-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="comparing-several-means-hummingbirds-and-tropical-flowers" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Comparing Several means: Hummingbirds and Tropical Flowers<a href="intro-to-anova-analysis.html#comparing-several-means-hummingbirds-and-tropical-flowers" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Ethan Temeles and W. John Kress of Amherst College studied the relationship between varieties of the tropical flower Heliconia on the island of Dominica and the different species of hummingbirds that pollinate the flowers. Over time, the researchers believe, the lengths of the flowers and the forms of the hummingbirds’ beaks have evolved to match each other. If that is true, flower varieties pollinated by different hummingbird species should have distinct distributions of length.</p>
<p>The table below gives length measurements (in millimeters) for random samples of three varieties of Heliconia, each pollinated by a different species of humming- bird. Do the three varieties display distinct distributions of length? In particular, do the mean lengths of their flowers differ?</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="intro-to-anova-analysis.html#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb53-2"><a href="intro-to-anova-analysis.html#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb53-3"><a href="intro-to-anova-analysis.html#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggthemes)</span></code></pre></div>
<p>For the flower data, I made a CSV file from the textbook data, and then imported it into R.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="intro-to-anova-analysis.html#cb54-1" aria-hidden="true" tabindex="-1"></a>Flowers<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;resources/data/Flowers.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 23 Columns: 3
## ── Column specification ───────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (3): H. bihai, H. caribea red, H. caribea yellow
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="intro-to-anova-analysis.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Flowers)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   `H. bihai` `H. caribea red` `H. caribea yellow`
##        &lt;dbl&gt;            &lt;dbl&gt;               &lt;dbl&gt;
## 1       47.1             41.9                36.8
## 2       46.8             42.0                37.0
## 3       46.8             41.9                36.5
## 4       47.1             43.1                36.1
## 5       46.7             41.5                36.0
## 6       47.4             41.7                35.4</code></pre>
<p>In order for R to process the data, I need to convert the data from “wide” format to “long” format. I also need to let R know that each species should be treated as a “factor,” which means that it is a type of categorical variable (so I can sort out data based on Species) later on.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="intro-to-anova-analysis.html#cb58-1" aria-hidden="true" tabindex="-1"></a>Flowers_long<span class="ot">&lt;-</span> <span class="fu">gather</span>(Flowers, <span class="st">&quot;Species&quot;</span>, <span class="st">&quot;Length&quot;</span>, <span class="at">factor_key=</span> <span class="cn">TRUE</span>)</span>
<span id="cb58-2"><a href="intro-to-anova-analysis.html#cb58-2" aria-hidden="true" tabindex="-1"></a>Flowers_long</span></code></pre></div>
<pre><code>## # A tibble: 69 × 2
##    Species  Length
##    &lt;fct&gt;     &lt;dbl&gt;
##  1 H. bihai   47.1
##  2 H. bihai   46.8
##  3 H. bihai   46.8
##  4 H. bihai   47.1
##  5 H. bihai   46.7
##  6 H. bihai   47.4
##  7 H. bihai   46.4
##  8 H. bihai   46.6
##  9 H. bihai   48.1
## 10 H. bihai   48.3
## # … with 59 more rows</code></pre>
<p>Let’s follow the strategy we learned way back in Unit 1: use graphs and numerical summaries to compare the three distributions of flower length. Here are the summary statistics we will use in further analysis:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="intro-to-anova-analysis.html#cb60-1" aria-hidden="true" tabindex="-1"></a>mean_and_sd<span class="ot">&lt;-</span> Flowers_long <span class="sc">%&gt;%</span></span>
<span id="cb60-2"><a href="intro-to-anova-analysis.html#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb60-3"><a href="intro-to-anova-analysis.html#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mean=</span><span class="fu">mean</span>(Length, <span class="at">na.rm=</span>T), </span>
<span id="cb60-4"><a href="intro-to-anova-analysis.html#cb60-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sd=</span><span class="fu">sd</span>(Length, <span class="at">na.rm=</span>T))</span>
<span id="cb60-5"><a href="intro-to-anova-analysis.html#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="intro-to-anova-analysis.html#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mean_and_sd)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   Species            mean    sd
##   &lt;fct&gt;             &lt;dbl&gt; &lt;dbl&gt;
## 1 H. bihai           47.6 1.21 
## 2 H. caribea red     39.7 1.80 
## 3 H. caribea yellow  36.2 0.975</code></pre>
<p>What do we see? The three varieties differ so much in flower length that there is little overlap among them. In particular, the flowers of bihai are longer than either red or yellow. The mean lengths are 47.6 mm for H. bihai, 39.7 mm for H. caribaea red, and 36.2 mm for H. caribaea yellow. Are these observed differences in sample means statistically significant? We must develop a test for comparing more than two population means.</p>
</div>
<div id="the-f-test" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> The F Test<a href="intro-to-anova-analysis.html#the-f-test" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We want to test the null hypothesis that there are no differences among the mean lengths for the three populations of flowers:</p>
<p>H0:μ1 =μ2 =μ3</p>
<p>The alternative hypothesis is that there is some difference. That is, not all three population means are equal:</p>
<p>Ha : not all of μ1, μ2, and μ3 are equal</p>
<p>The alternative hypothesis is no longer one-sided or two-sided. It is “many-sided” because it allows any relationship other than “all three equal.”</p>
<p>For example, Ha includes the case in which m2 = m3 but m1 has a different value.</p>
<p>When the conditions for inference are met, the appropriate significance test for comparing means is the analysis of variance F test. Analysis of variance is usually abbreviated as ANOVA.</p>
</div>
<div id="check-for-conditions" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Check for Conditions<a href="intro-to-anova-analysis.html#check-for-conditions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have stated our Null and Alternative Hypotheses, we can check for conditions:</p>
<ul>
<li><p>Random: Researchers took separate random samples of 16 bihaii, 23 red, and 15 Heliconia flowers.</p></li>
<li><p>Normal: We entered the data into R and made side by side boxplots. Although the distributions for the bihai and red varieties show some right-skewness, we don’t see nay strong skewness or outliers that would prevent the use of one-way ANOVA.</p></li>
</ul>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="intro-to-anova-analysis.html#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(Flowers_long, <span class="fu">aes</span>(<span class="at">x=</span>Length, <span class="at">y=</span>Species, <span class="at">fill=</span>Species))<span class="sc">+</span></span>
<span id="cb62-2"><a href="intro-to-anova-analysis.html#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">color=</span><span class="st">&quot;black&quot;</span>)<span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span> <span class="st">&quot;Flower Lengths from Textbook&quot;</span>)<span class="sc">+</span><span class="fu">theme_gdocs</span>()<span class="sc">+</span> <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.1</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 15 rows containing non-finite values (stat_boxplot).</code></pre>
<pre><code>## Warning: Removed 15 rows containing missing values (geom_point).</code></pre>
<p><img src="book_temp_files/figure-html/boxplot%20Flowers-1.png" width="672" /></p>
<ul>
<li><p>Independent: Researchers took independent samples of bihai, red, and yellow Heliconia. because sampling without replacement was used, there must be at least 10(16) = 160 bihai, 10(23) = 230 red, and 10(15) = 150 yellow flowers. This is pretty safe to assume.</p></li>
<li><p>Same SD: In a one-way ANOVA, you must check whether the largest sample SD divided by the smallest SD has a ratio less than 2. Our sample standard deviations are:</p></li>
</ul>
<pre><code>## # A tibble: 3 × 3
##   Species            mean    sd
##   &lt;fct&gt;             &lt;dbl&gt; &lt;dbl&gt;
## 1 H. bihai           47.6 1.21 
## 2 H. caribea red     39.7 1.80 
## 3 H. caribea yellow  36.2 0.975</code></pre>
<p>These standard deviations satisfy our rule of thumb that (largest SD)/ (smallest SD) is less than 2, so we can proceed.</p>
<p>Since we have satifised all 3 conditions, we can safely use ANOVA to compare the mean lengths of the three populations.</p>
</div>
<div id="the-f-distribution" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> The F Distribution<a href="intro-to-anova-analysis.html#the-f-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The variances for <em>three</em> populations is naturally larger than the variance of two populations. Just like how two populations naturally have a larger variance, and thus requires the t-distribution (which has more “area” under the tails), we need to use a different distribution that takes into account this larger variance (which has even more “area” under the tails. This distribution is called the <strong>F-Distribution</strong>.</p>
<p><img src="resources/images/03-ANOVA-Analysis/F_Dist.png" width="35%" style="float:right; padding:10px" /></p>
<p>The <strong><code>*F* distributions</code></strong> are a family of right-skewed distributions that take only values greater than 0. Above are some possible shapes. A specific F distribution is determined by the degrees of freedom of the numerator and denominator of the F statistic. When describing an F distribution, always give the numerator degrees of freedom first. Our notation will be F (df1, df2) for the F distribution with df1 degrees of freedom in the numerator and df2 degrees of freedom in the denominator. <em>Interchanging the degrees of freedom changes the distribution, so the order is important. </em></p>
<div id="finding-the-degrees-of-freedom-for-f" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Finding the Degrees of Freedom for F<a href="intro-to-anova-analysis.html#finding-the-degrees-of-freedom-for-f" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the two earlier examples, we compared the mean lengths for three varieties of flowers,so k=3.The three sample sizes are n1 =16,n2 =23,and n3 =15. The total number of observations is therefore N = 16 + 23 + 15 = 54. The ANOVA F test has numerator degrees of freedom
<img src="resources/images/03-ANOVA-Analysis/F_Dist_Overview.png" width="55%" style="float:right; padding:10px" /></p>
<p>k - 1 = 3 - 1 = 2</p>
<p>and denominator degrees of freedom</p>
<p>N - k = 54 - 3 = 51</p>
</div>
<div id="understanding-the-f-statistic" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Understanding the F Statistic<a href="intro-to-anova-analysis.html#understanding-the-f-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like we had a test statistic in a two-sample t-test, we need something similar to tell us the distance the statistic is away from our Null Hypothesis. This distance is called the F Statistic.</p>
<p>The F Statistic is calculated by doing:</p>
<p><span class="math display">\[ F= \frac{\text{variation among the sample means}}{\text{variation among individuals within the same sample}} \]</span></p>
<p>Specifically, the variation is calculated by dividing the <em>Mean Square for Groups</em> by the <em>Mean Square for Error</em>. The statistic is reproduced below, but you should know that you’d never have to do this by hand– R will do it all for you.</p>
<p><img src="resources/images/03-ANOVA-Analysis/ANOVA_F_Test.png" width="45%" /></p>
</div>
<div id="calculate-the-f-statistic" class="section level3 hasAnchor" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Calculate the F Statistic<a href="intro-to-anova-analysis.html#calculate-the-f-statistic" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Just like we had a test statistic in a two-sample t-test, we need something similar to tell us the <em>distance</em> the statistic is away from our Null Hypothesis. This distance is called the F Statistic.</p>
<p>The F Statistic is calculated by doing:</p>
</div>
</div>
<div id="conducting-the-one-way-anova" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Conducting the one-way ANOVA<a href="intro-to-anova-analysis.html#conducting-the-one-way-anova" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Of course, the previous pages gave you a <em>very</em> brief background of a one-way ANOVA test.</p>
<p>It turns out that conducting the test itself in R is very easy– R even calculates the degrees of freedom for you.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="intro-to-anova-analysis.html#cb66-1" aria-hidden="true" tabindex="-1"></a>Flowers_long <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(Flowers_long)</span>
<span id="cb66-2"><a href="intro-to-anova-analysis.html#cb66-2" aria-hidden="true" tabindex="-1"></a>anova.test <span class="ot">&lt;-</span> <span class="fu">aov</span>(Length <span class="sc">~</span> Species, <span class="at">data=</span><span class="fu">na.omit</span>(Flowers_long))</span>
<span id="cb66-3"><a href="intro-to-anova-analysis.html#cb66-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova.test)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)    
## Species      2 1082.9   541.4   259.1 &lt;2e-16 ***
## Residuals   51  106.6     2.1                   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Looking at the P Value for Species, the one-way ANOVA Test tells us that there is a very significant difference between the average lengths of the 3 species. Thus, we reject the Null Hypothesis, and in favor of the Alternative Hypothesis that ther <em>is</em> a significant difference between the three species.</p>
</div>
<div id="conclude-pt.-2-creating-tukey-post-hoc-pairwise-comparisons" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Conclude Pt. 2: Creating Tukey Post-Hoc Pairwise Comparisons<a href="intro-to-anova-analysis.html#conclude-pt.-2-creating-tukey-post-hoc-pairwise-comparisons" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Knowing that there is a difference is often not enough– what if you want to know exactly <em>which</em> means were significantly different from each other? In this case, we’d have to conduct a two-sample t-test for every possible two means that we have, which could be irritating, especially if we are comparing many means with each other.</p>
<p>This is where a Tukey Post-Hoc Pairwise Comparison comes into play. The name sounds scary, but the following is true:</p>
<ul>
<li><p>A guy named Tukey created this method.</p></li>
<li><p>“Post-Hoc” means “after the fact” in Latin. After knowing the fact that there is a difference among all three means from a one-way ANOVA, you can perform this procedure.</p></li>
<li><p>“Pairwise Comparision” means you compare two things with each other.</p></li>
</ul>
<p>To perform the pairwise comparison, run the <em>TukeyHSD()</em> command on your anova.test model.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="intro-to-anova-analysis.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(anova.test, <span class="at">conf.level=</span>.<span class="dv">95</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Length ~ Species, data = na.omit(Flowers_long))
## 
## $Species
##                                        diff        lwr        upr
## H. caribea red-H. bihai           -7.886196  -9.022163  -6.750229
## H. caribea yellow-H. bihai       -11.417500 -12.671601 -10.163399
## H. caribea yellow-H. caribea red  -3.531304  -4.689387  -2.373222
##                                  p adj
## H. caribea red-H. bihai              0
## H. caribea yellow-H. bihai           0
## H. caribea yellow-H. caribea red     0</code></pre>
<p>You can also plot these results, as shown below:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="intro-to-anova-analysis.html#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Margins will spill over, so you need to adjust these</span></span>
<span id="cb70-2"><a href="intro-to-anova-analysis.html#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">13</span>, <span class="dv">4</span>, <span class="dv">4</span>)<span class="sc">+</span><span class="fl">0.1</span>)</span>
<span id="cb70-3"><a href="intro-to-anova-analysis.html#cb70-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-4"><a href="intro-to-anova-analysis.html#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">TukeyHSD</span>(anova.test, <span class="at">conflevel=</span>.<span class="dv">95</span>), <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<p><img src="book_temp_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Notice that the x-axis doesn’t even include 0– our pairwise comparisons illustrate that all of the species are significantly different from each other in terms of mean length. Notice that none of the confidence intervals include 0 (what does that mean?).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro-to-two-sample-t-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="book_assets/gitbook-2.6.7/js/app.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="book_assets/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="book_assets/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
